drdrerde/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('songs.urls', namespace='songs')),
]

songs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    # Songs page
    url(r'^songs/$', views.songs, name='songs'),
    # Page for an individual song
    url(r'^song/(?P<song_id>\d+)/$', views.song, name="song"),
]

songs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Song(models.Model):
   
    english_title = models.CharField(max_length=200)
    arabic_title = models.CharField(max_length=200)
    german_title = models.CharField(max_length=200)

    english_text = models.TextField()
    arabic_text = models.TextField()
    german_text = models.TextField()

    def __str__(self):
        return self.english_title

songs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from .models import Song

# Create your views here.

def index(request):
    """Home page"""
    return render(request, 'songs/index.html')

def songs(request):
    """Songs page"""
    songs = Song.objects.order_by()
    context = {'songs':songs}
    return render(request, 'songs/songs.html', context)

def song(request, song_id):
    """Page for an individual song"""
    songs = Song.objects.get(id=song_id)
    
    english_title = songs.english_title
    arabic_title = songs.arabic_title
    german_title = songs.german_title
    english_text = songs.english_text
    arabic_text = songs.arabic_text
    german_text = songs.german_text

    context = {'songs':songs, 'english_title':english_title, 'arabic_title':arabic_title, 'german_title':german_title, 'english_text':english_text, 'arabic_text':arabic_text, 'german_text':german_text}
    return render(request, 'songs/song.html', context)

songs/templates/songs/base.html
<html>
  <head>
    <title>Dr. Dr. Erde's Wonderful World</title>
    <link href="/static/songs/base.css" type="text/css" rel="stylesheet" />
  </head>
  <header>
    <h1>Dr. Dr. Erde's Wonderful World</h1>
    <h3>Learn languages with music</h3>
  </header>
  <nav>
    <h3>
      <a href="{% url 'songs:index' %}">Home</a>
      <a href="{% url 'songs:songs' %}">Songs</a>
    </h3>
  </nav>
  <body>
    <div id="content">
      {% block content %} {% endblock content %}
    </div>
  </body>
</html>

songs/templates/songs/index.html
{% extends "songs/base.html" %}

{% block content %}
<style>
  body {background-image: url("/static/songs/earth.jpg");
        background-repeat: no-repeat;}
</style>

{% endblock content %}

songs/templates/songs/song.html
{% extends "songs/base.html" %}

{% block content %}
<script> 
  function toggleLanguage(language){
    var elements = document.getElementsByClassName(language);
    for(var i = 0; i < elements.length; i++){
      if (elements[i].style.display !== 'none'){
        elements[i].style.display = 'none';
      }
      else {elements[i].style.display = 'table-cell';}
    }
  }
</script>

<p>Toggle Languages: <button onclick="toggleLanguage('english')">English </button> <button onclick="toggleLanguage('arabic')">عربى </button> <button onclick="toggleLanguage('german')">Deutsche </button> </p>
<table>
<tr>
  <th class='english'>{{english_title|linebreaks}}</th>
  <th class='arabic'>{{arabic_title|linebreaks}}</th>
  <th class='german'>{{german_title|linebreaks}}</th>
</tr>
<tr>
  <td class='english'>{{english_text|linebreaks}}</td>
  <td class='arabic'>{{arabic_text|linebreaks}}</td>
  <td class='german'>{{german_text|linebreaks}}</td>
</tr>
</table>

{% endblock content %}

songs/templates/songs/songs.html
{% extends "songs/base.html" %}

{% block content %}

<h3>Songs</h3>

<ul>
  {% for song in songs %}
    <li><a href="{% url 'songs:song' song.id %}">{{ song }}</a></li>
  {% empty %}
    <li>No song titles found</li>
  {% endfor %}
</ul>

{% endblock content %}